# Generated by Django 6.1.1 on 2026-09-14 02:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_site_context(apps, schema_editor):
    PermafrostRole = apps.get_model("permafrost", "PermafrostRole")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    site_content_type, created = ContentType.objects.db_manager(db_alias).get_or_create(
        app_label="sites",
        model="site",
    )

    for role in PermafrostRole.objects.using(db_alias).all():
        role.context_content_type = site_content_type
        role.context_object_id = role.site_id
        role.save(
            update_fields=[
                "context_content_type",
                "context_object_id",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("permafrost", "0019_auto_20210406_1820"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="permafrostrole",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="permafrostrole",
            name="context_content_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Context content type",
            ),
        ),
        migrations.AddField(
            model_name="permafrostrole",
            name="context_object_id",
            field=models.PositiveBigIntegerField(
                blank=True, editable=False, null=True, verbose_name="Context object ID"
            ),
        ),
        migrations.RunPython(backfill_site_context, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="permafrostrole",
            constraint=models.UniqueConstraint(
                fields=("name", "context_content_type", "context_object_id"),
                name="unique_permafrost_role_name_per_context",
            ),
        ),
    ]
