# Generated by Django 6.1.1 on 2026-09-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permafrost", "0020_alter_permafrostrole_unique_together_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permafrostrole",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permafrost_role",
                to="sites.site",
            ),
        ),
    ]
