# Generated by Django 2.2.10 on 2020-02-04 21:13

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('category', models.IntegerField(verbose_name='Role Category')),
                ('settings', models.TextField(verbose_name='Settings')),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('category', models.IntegerField(verbose_name='Role Category')),
                ('settings', models.TextField(verbose_name='Settings')),
                ('deleteable', models.BooleanField(verbose_name='Deleteable')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='')),
                ('role_permissions', models.ManyToManyField(related_name='roles', to='permafrost.RolePermission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
