# Generated by Django 2.2.10 on 2020-02-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permafrost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Role Permission'),
        ),
    ]
