# Generated by Django 2.2.10 on 2020-02-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permafrost', '0002_auto_20200204_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='category',
        ),
        migrations.RemoveField(
            model_name='role',
            name='deleteable',
        ),
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='settings',
        ),
    ]
