# Generated by Django 2.2.10 on 2020-02-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permafrost', '0003_auto_20200204_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.IntegerField(choices=[(1, 'User'), (30, 'Staff'), (50, 'Administrator')], default=1, verbose_name='Role Category'),
        ),
        migrations.AddField(
            model_name='role',
            name='settings',
            field=models.TextField(blank=True, null=True, verbose_name='Settings'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='category',
            field=models.IntegerField(choices=[(1, 'User'), (30, 'Staff'), (50, 'Administrator')], default=1, verbose_name='Role Category'),
        ),
    ]
