# Generated by Django 2.2.10 on 2020-02-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('permafrost', '0004_auto_20200204_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='settings',
            field=models.TextField(blank=True, null=True, verbose_name='Settings'),
        ),
    ]
