# Generated by Django 2.2.10 on 2020-02-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('permafrost', '0005_auto_20200204_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Django Permission'),
            preserve_default=False,
        ),
    ]
