# Generated by Django 2.2.10 on 2020-02-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permafrost', '0006_rolepermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='category',
            field=models.IntegerField(choices=[(1, 'User'), (30, 'Staff'), (50, 'Administrator')], default=1, verbose_name='Role Category Level'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
