# Generated by Django 2.2.10 on 2020-02-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permafrost', '0007_auto_20200204_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['name'], 'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AddField(
            model_name='role',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='role_permissions',
            field=models.ManyToManyField(related_name='roles', to='permafrost.RolePermission', verbose_name='Permissions'),
        ),
    ]
