# Generated by Django 2.2.10 on 2020-02-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('permafrost', '0008_auto_20200204_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Groups'),
            preserve_default=False,
        ),
    ]
