# Generated by Django 3.1.3 on 2020-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permafrost', '0017_delete_permafrostcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='permafrostrole',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
